site_name: hIPPYlib
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages
- mdx_math # MathJax extension. Use \(...\) for inline; \[ ...\] for standalone math

repo_url: https://github.com/hippylib/hippylib

pages:
- Home: index.md
- Features: features.md
- Documentation:
  - 'Installing hIPPYlib': building.md
  - 'Tutorial': tutorial.md
  - 'Publications': publications.md
  - 'Outreach': outreach.md
- Download: download.md
- 'About': about.md

#theme_dir: template
theme: spacelab

include_next_prev: false  # turn of next/previous buttons

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
