site_name: hIPPYlib
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages
- mdx_math: # MathJax extension. Use \(...\) for inline; \[ ...\] for standalone math
    enable_dollar_delimiter: True # allows $...$ for inline math

repo_url: https://github.com/hippylib/hippylib

pages:
- Home: index.md
#- Features: features.md
- Tutorial:
      - README: tutorial.md
      - FEniCS101: tutorials/1_FEniCS101/index.md
      - Poisson Deterministic: tutorials/2_PoissonDeterministic/index.md
      - Subsurface Bayesian: tutorials/3_SubsurfaceBayesian/index.md
      - Advection-Diffusion Bayesian: tutorials/4_AdvectionDiffusionBayesian/index.md
      - Hessian Spectrum: tutorials/5_HessianSpectrum/index.md
- Installation: building.md
- Download: download.md
- Research: research.md
- Outreach: outreach.md
- Announcements: postdoc_position.md
- About: about.md

#theme_dir: template
theme: spacelab

google_analytics: ['UA-52448613-3', 'hippylib.github.io']

include_next_prev: false  # turn of next/previous buttons

extra_javascript: 
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    
copyright: Copyright &copy; 2016-2017 The University of Texas at Austin, University of California Merced. <br> This material is based on work partially supported by the National Science Foundation under Grants No ACI-1550593, ACI-1550547. 
