site_name: hIPPYlib
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages
- mdx_math: # MathJax extension. Use \(...\) for inline; \[ ...\] for standalone math
    enable_dollar_delimiter: True # allows $...$ for inline math

repo_url: https://github.com/hippylib/hippylib
edit_uri: ""

nav:
- Home: index.md
#- Features: features.md
- Tutorial: tutorial_v3.0.0.md
- Documentation: documentation.md
- Download: download.md
- Research: research.md
- Outreach: outreach.md
#- Openings: postdoc_position.md
- About: about.md

#theme_dir: template
theme:
  name: spacelab
  analytics:
    gtag: G-24ZCR56GPX


extra_javascript: 
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    
copyright: Copyright &copy; 2016-2023 The University of Texas at Austin, University of California Merced. <br> Copyright &copy; 2018-2020 The University of Texas at Austin, University of California Merced, Washington University in St. Louis. <br> This material is based on work partially supported by the National Science Foundation under Grants No ACI-1550593, ACI-1550547. 
