site_name: hIPPYlib
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages
- mdx_math: # MathJax extension. Use \(...\) for inline; \[ ...\] for standalone math
    enable_dollar_delimiter: True # allows $...$ for inline math

repo_url: https://github.com/hippylib/hippylib
edit_uri: ""

nav:
- Home: index.md
#- Features: features.md
- Tutorial:
      - Version 3.0.0:
          - README: tutorial_v3.0.0.md
          - FEniCS101: tutorials_v3.0.0/1_FEniCS101.md
          - Poisson Deterministic: tutorials_v3.0.0/2_PoissonDeterministic.md
          - Subsurface Bayesian: tutorials_v3.0.0/3_SubsurfaceBayesian.md
          - Advection-Diffusion Bayesian: tutorials_v3.0.0/4_AdvectionDiffusionBayesian.md
          - Hessian Spectrum: tutorials_v3.0.0/5_HessianSpectrum.md
      - Version 2.3.0:
          - README: tutorial_v2.3.0.md
          - FEniCS101: tutorials_v2.3.0/1_FEniCS101/1_FEniCS101.md
          - Poisson Deterministic: tutorials_v2.3.0/2_PoissonDeterministic/2_PoissonDeterministic.md
          - Subsurface Bayesian: tutorials_v2.3.0/3_SubsurfaceBayesian/3_SubsurfaceBayesian.md
          - Advection-Diffusion Bayesian: tutorials_v2.3.0/4_AdvectionDiffusionBayesian/4_AdvectionDiffusionBayesian.md
          - Hessian Spectrum: tutorials_v2.3.0/5_HessianSpectrum/5_HessianSpectrum.md
      - Version 1.6.0:
          - README: tutorial_v1.6.0.md
          - FEniCS101: tutorials_v1.6.0/1_FEniCS101/index.md
          - Poisson Deterministic: tutorials_v1.6.0/2_PoissonDeterministic/index.md
          - Subsurface Bayesian: tutorials_v1.6.0/3_SubsurfaceBayesian/index.md
          - Advection-Diffusion Bayesian: tutorials_v1.6.0/4_AdvectionDiffusionBayesian/index.md
          - Hessian Spectrum: tutorials_v1.6.0/5_HessianSpectrum/index.md
- Documentation: documentation.md
- Download: download.md
- Research: research.md
- Outreach: outreach.md
#- Openings: postdoc_position.md
- About: about.md

#theme_dir: template
theme: mkdocs

#google_analytics: ['UA-52448613-3', 'hippylib.github.io']

#analytics:
gtag:
    - G-24ZCR56GPX


extra_javascript: 
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    
copyright: Copyright &copy; 2016-2018 The University of Texas at Austin, University of California Merced. <br> Copyright &copy; 2018-2020 The University of Texas at Austin, University of California Merced, Washington University in St. Louis. <br> This material is based on work partially supported by the National Science Foundation under Grants No ACI-1550593, ACI-1550547. 
